services:
  ros-container:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
        USERNAME: ${USER:-robat}
    image: force_estimation-docker:jazzy-cuda
    container_name: force_estimation_container
    network_mode: host
    gpus: all
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
      - COLCON_PYTHON_EXECUTABLE=/opt/venv/bin/python3
      - Python3_EXECUTABLE=/opt/venv/bin/python3
    volumes:
      # bind your repo
      - ${APE_REPO:-$HOME/.localgit/algorithmic_payload_estimation}:/ros2_ws/src/algorithmic_payload_estimation:rw
      # X11 for RViz
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # ssh-agent for private submodules
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    working_dir: /ros2_ws
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        rosdep update &&
        rosdep install --from-paths src --rosdistro jazzy --ignore-src -r -y &&
        colcon build --symlink-install
        exec bash
      "

    stdin_open: true
    tty: true
    restart: "no"