services:
  ros-container:
    build: 
      context: .
      dockerfile: Dockerfile.simulation
    image: force_estimation-docker
    container_name: force_estimation_container
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Share X11 socket for GUI applications
      - /home/robat/.localgit/algorithmic_payload_estimation:/catkin_ws/src/algorithmic_payload_estimation

    stdin_open: true
    tty: true
    restart: no
