services:
  ros-container:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
        USERNAME: ${USER:-robat}
    image: force_estimation-docker:jazzy-cuda
    container_name: force_estimation_container
    network_mode: host
    gpus: all
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=0
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
      - COLCON_PYTHON_EXECUTABLE=/opt/venv/bin/python3
    volumes:
      # bind your repo
      - ${APE_REPO:-$HOME/.localgit/algorithmic_payload_estimation}:/ros2_ws/src/algorithmic_payload_estimation:rw
      # X11 for RViz
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # ssh-agent for private submodules
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    working_dir: /ros2_ws
    # command: >
    #   bash -lc '
    #     set -euxo pipefail;
    #     source /opt/ros/jazzy/setup.bash;

    #     # ensure dirs exist & are writable (no named volumes now; this is quick)
    #     mkdir -p /ros2_ws/{build,install,log};

    #     # git safe dir (when mapped UID/GID differs)
    #     git config --global --add safe.directory /ros2_ws/src/algorithmic_payload_estimation || true;

    #     # submodules pinned to committed SHAs
    #     cd /ros2_ws/src/algorithmic_payload_estimation;
    #     git submodule sync --recursive;
    #     git submodule update --init --recursive;

    #     cd /ros2_ws;
    #     sudo apt-get update -y || true;
    #     sudo rosdep update || true;
    #     sudo rosdep install --from-paths src --rosdistro jazzy -y --ignore-src || true;

    #     colcon build --symlink-install || { echo "[WARN] colcon failed; dropping to shell"; exec bash; }
    #     exec bash
    #   '
    stdin_open: true
    tty: true
    restart: "no"