services:
  isaac-lab-ros2:
    ipc: host
    environment:
      # Core ROS 2 / DDS
      ROS_DISTRO: "humble"
      RMW_IMPLEMENTATION: "rmw_cyclonedds_cpp"
      ROS_DOMAIN_ID: "0"
      ROS_LOCALHOST_ONLY: "0"
      FASTRTPS_DEFAULT_PROFILES_FILE: ""   # ensure Fast DDS XML isn't injected
      ROS2CLI_NO_DAEMON: "1"

      # Isaac Sim path hint (used by some tools/extensions)
      isaac_sim_package_path: "/isaac-sim"

      # Keep Isaac's Python (3.11) clean of Humble's 3.10 site-packages
      PYTHONPATH: ""

      # Make your robot pkgs discoverable to URDF importer / tools
      ROS_PACKAGE_PATH: "/ros_pkgs/Universal_Robots_ROS2_Description:/ros_pkgs/ur_manipulator_description:/ros_pkgs/ur_manipulator_moveit_config"
    volumes:
      # Bind-mount your robot description/config packages into a single root
      - ${APE_REPO}/Universal_Robots_ROS2_Description:/ros_pkgs/Universal_Robots_ROS2_Description:rw
      - ${APE_REPO}/ur_manipulator_description/ur_manipulator_description:/ros_pkgs/ur_manipulator_description:rw
      - ${APE_REPO}/ur_manipulator_moveit_config/ur_manipulator_moveit_config:/ros_pkgs/ur_manipulator_moveit_config:rw