services:
  isaac-lab-ros2:
    network_mode: host
    ipc: host
    environment:
      ROS_DISTRO: "humble"
      RMW_IMPLEMENTATION: "rmw_cyclonedds_cpp"
      ROS_DOMAIN_ID: "0"
      ROS_LOCALHOST_ONLY: "0"
      ROS2CLI_NO_DAEMON: "1"

      # Ament index: your overlay + Isaac’s bridge
      AMENT_PREFIX_PATH: "/workspace/ros_ws/install:/isaac-sim/exts/isaacsim.ros2.bridge/humble"

      # Use Isaac’s Python 3.11 rclpy (no /opt/ros on PYTHONPATH)
      PYTHONPATH: "/isaac-sim/exts/isaacsim.ros2.bridge/humble/lib/python3.11/site-packages"

      # Optional: helps the *normal* URDF importer before first build
      # (point to package roots inside the mounted workspace)
      ROS_PACKAGE_PATH: >
        /workspace/ros_ws/src/Universal_Robots_ROS2_Description:/workspace/ros_ws/src/manipulator_description/ur_manipulator_description:/workspace/ros_ws/src/manipulator_moveit_config/ur3_manipulator_moveit_config

      isaac_sim_package_path: "/isaac-sim"
      FASTRTPS_DEFAULT_PROFILES_FILE: ""

    volumes:
      # persist the overlay so build/install/log survive container restarts
      - ${APE_REPO}/isaac_ros_ws:/workspace/ros_ws

      # mount packages directly into the workspace src/
      - ${APE_REPO}/Universal_Robots_ROS2_Description:/workspace/ros_ws/src/Universal_Robots_ROS2_Description:ro
      - ${APE_REPO}/manipulator_description/ur_manipulator_description:/workspace/ros_ws/src/manipulator_description/ur_manipulator_description:ro
      - ${APE_REPO}/manipulator_moveit_config/ur3_manipulator_moveit_config:/workspace/ros_ws/src/manipulator_moveit_config/ur3_manipulator_moveit_config:ro

      # writable USD output (saved into your repo)
      - ${APE_REPO}/manipulator_description/ur_manipulator_description/usd:/workspace/usd