services:
  isaac-lab-ros2:
    ipc: host
    # network_mode: host   # only if needed; IsaacLab usually already sets this
    environment:
      # required by your check
      isaac_sim_package_path: "/isaac-sim"
      ROS_DISTRO: "humble"

      # Cyclone + ROS2 CLI stability
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      ROS_DOMAIN_ID: "0"
      FASTRTPS_DEFAULT_PROFILES_FILE: ""
      ROS2CLI_NO_DAEMON: "1"

      # prepend Isaac bridge lib, keep existing paths
      LD_LIBRARY_PATH: "/isaac-sim/exts/isaacsim.ros2.bridge/humble/lib:${LD_LIBRARY_PATH}"