manipulator:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint
  gains:
    ur5_shoulder_pan_joint:
      p: 4000
      d: 200
      i: 1
      i_clamp: 1
    ur5_shoulder_lift_joint:
      p: 10000
      d: 200
      i: 1
      i_clamp: 1
    ur5_elbow_joint:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
    ur5_wrist_1_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1
    ur5_wrist_2_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1
    ur5_wrist_3_joint:
      p: 10
      d: 0.1
      i: 0
      i_clamp: 1