joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 125

manipulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints: &robot_joints
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint
  trajectory_execution:
    trajectory_duration_monitoring: False
  gains:
    ur5_shoulder_pan_joint: {p: 4000, i: 1, d: 200, i_clamp: 1}
    ur5_shoulder_lift_joint: {p: 10000, i: 1, d: 200, i_clamp: 1}
    ur5_elbow_joint: {p: 2000, i: 1, d: 20, i_clamp: 1}
    ur5_wrist_1_joint: {p: 500, i: 1, d: 1, i_clamp: 1}
    ur5_wrist_2_joint: {p: 500, i: 1, d: 1, i_clamp: 1}
    ur5_wrist_3_joint: {p: 10, i: 1, d: 0.1, i_clamp: 1}
  constraints:
    goal_time: 3.0
    stopped_velocity_tolerance: 1.0
    ur5_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    ur5_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    ur5_elbow_joint: {trajectory: 0.1, goal: 0.1}
    ur5_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    ur5_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    ur5_wrist_3_joint: {trajectory: 0.1, goal: 0.1}

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_finger_joint
  gains:
    gripper_finger_joint: {p: 100, i: 1, d: 1, i_clamp: 1}